FROM node:latest

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
        build-essential \
        python3 && \
    rm -fr /var/lib/apt/lists/* && \
    rm -rf /etc/apt/sources.list.d/*

RUN npm -global --quiet install truffle

COPY . .
RUN chmod u+x verify_proof.sh
